### ISSUE TITLE
Cross origin iframe support

### ISSUE THREAD

**Issue by jvanderwel-ct** [computestdev/Openrunner#41]
Same origin iframes are supported because we can set `bluefox.target(iframe.contentWindow)`
However we will have to implement something different for cross origin iframes.
This may also require some clean up in the background<->content script communication framework, to make it more lightweight.

**Comment by Joris-van-der-Wel** [comment]
Fixed by 19880fa30fcf1f0a3d937ac58fe83c8b18e74ed4 0a4f172b92cc20744c61c9408a2c43932f9a011d f5bc68d673b526337a077c3ef2c0443b0d558631
